config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_page#index'
  resources :games 
  resources :get_pieces
  resources :pieces
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chessmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-toggleable-lg navbar-light bg-light">


  <button class="navbar-toggler ml-auto logo-box float-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse align-items-center" id="navbarTogglerDemo02">
  <ul class="navbar-nav mr-auto mt-2 mt-lg-0 align-items-center">
  <%= link_to root_path do %>
    <span class="navbar-brand logo-box"><p class="navbrand-text"><i class="fas fa-chess-pawn"></i>Chessmate</p></span>
  <% end %>

    <li class="nav-item nav-link">
      <%= link_to 'Create Game', new_game_path, class: "create-link" %>   
    </li>
    <li class="nav-item nav-link">
      <%= link_to 'Dashboard', games_path, class: "create-link" %>

    </li>
  </ul>
  <ul class="nav navbar-nav float-lg-right">
                                                                <!-- User Drop Down menu -->
  <% if user_signed_in? %>                                  
        <li class="nav-item user-name">
          <a>Signed in as <%= current_user.email %></a>
        </li>

        <li class="nav-item">
          <div class="dropdown align-items-center">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="dropdownMenuButton">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "drop-items" %>
          </div>
          </div>
        </li>

      <% else %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Log in!
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary login-dropdown top-login' %>
            <br />
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary login-dropdown' %>
          </div>
        </div>
      <% end %>
    </ul>
</div>
</nav>
    <%= yield %>



<footer class="footer page-footer font-small blue pt-4">
  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Placeholder Footer</p>

      </div>
      <hr class="clearfix w-100 d-md-none pb-3">

      <div class="col-md-3 mb-md-0 mb-3">

        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

</footer>
<!-- Footer -->
  </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chessmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-toggleable-lg navbar-light bg-light">


  <button class="navbar-toggler ml-auto logo-box float-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


<div class="collapse navbar-collapse align-items-center" id="navbarTogglerDemo02">
  <ul class="navbar-nav mr-auto mt-2 mt-lg-0 align-items-center">
  <%= link_to root_path do %>
    <span class="navbar-brand logo-box"><p class="navbrand-text"><i class="fas fa-chess-pawn"></i>Chessmate</p></span>
  <% end %>

    <li class="nav-item nav-link">
      <%= link_to 'Create Game', new_game_path, class: "create-link" %>
    </li>
    <li class="nav-item nav-link">
      <%= link_to 'Dashboard', games_path, class: "create-link" %>

    </li>
  </ul>
  <ul class="nav navbar-nav float-lg-right">
                                                                <!-- User Drop Down menu -->
  <% if user_signed_in? %>                                  
        <li class="nav-item user-name">
          <a>Signed in as <%= current_user.email %></a>
        </li>

        <li class="nav-item">
          <div class="dropdown align-items-center">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user"></i>
          </button>
          <div class="dropdown-menu dropdown-menu-right text-right" aria-labelledby="dropdownMenuButton">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "drop-items" %>
          </div>
          </div>
        </li>

      <% else %>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Log in!
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary login-dropdown top-login' %>
            <br />
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary login-dropdown' %>
          </div>
        </div>
      <% end %>
    </ul>
</div>
</nav>



<%= yield %>
  </body>
</html>